######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 21 23:21:15 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              include \
              src \
              ui \
              include\config \
              include\log \
              include\point \
              include\tools \
              src\config \
              src\log \
              src\point \
              src\tools \
              include\modbus\address \
              include\modbus\analyzer \
              include\modbus\comm \
              include\modbus\config \
              include\modbus\diagram \
              include\modbus\gui \
              include\modbus\io \
              include\modbus\station \
              include\tools\serial_test \
              src\modbus\address \
              src\modbus\analyzer \
              src\modbus\comm \
              src\modbus\config \
              src\modbus\diagram \
              src\modbus\gui \
              src\modbus\io \
              src\modbus\station \
              src\tools\serial_test
INCLUDEPATH += .

# Input
HEADERS += include/cms_config.h \
           include/main_window.h \
           include/config/cms_config_db.h \
           include/log/log_data_model.h \
           include/log/log_sender.h \
           include/log/log_server.h \
           include/log/log_widget.h \
           include/point/point_item_delegate.h \
           include/point/point_record.h \
           include/point/points_list_model.h \
           include/point/points_list_view.h \
           include/point/points_list_widget.h \
           include/tools/hex_convertor_widget.h \
           include/modbus/address/addr_space.h \
           include/modbus/address/addr_space_model.h \
           include/modbus/address/addr_space_view.h \
           include/modbus/analyzer/mbs_analyzer.h \
           include/modbus/comm/mbs_comm_model.h \
           include/modbus/comm/mbs_comm_view.h \
           include/modbus/config/config_item_delegate.h \
           include/modbus/config/master_config.h \
           include/modbus/config/master_config_model.h \
           include/modbus/config/master_config_view.h \
           include/modbus/config/mbs_def.h \
           include/modbus/config/serial_port_info.h \
           include/modbus/config/tcp_port_info.h \
           include/modbus/diagram/crc_check.h \
           include/modbus/diagram/diagram_validator.h \
           include/modbus/diagram/mbs_serial_master.h \
           include/modbus/diagram/mbs_serial_req_handler.h \
           include/modbus/diagram/mbs_serial_request.h \
           include/modbus/diagram/mbs_serial_response.h \
           include/modbus/diagram/mbs_tcp_master.h \
           include/modbus/diagram/mbs_tcp_req_handler.h \
           include/modbus/diagram/mbs_tcp_request.h \
           include/modbus/diagram/mbs_tcp_response.h \
           include/modbus/gui/addr_space_widget.h \
           include/modbus/gui/master_config_widget.h \
           include/modbus/gui/mbs_widget.h \
           include/modbus/io/mbs_serial_io.h \
           include/modbus/io/mbs_tcp_io.h \
           include/modbus/io/serial_master_session.h \
           include/modbus/io/serial_slave_session.h \
           include/modbus/io/tcp_master_session.h \
           include/modbus/io/tcp_slave_session.h \
           include/modbus/station/modbus_station.h \
           include/tools/serial_test/serial_test_widget.h
FORMS += ui/hex_convertor_widget.ui ui/mbs_widget.ui ui/serial_test_widget.ui
SOURCES += src/comm_svr_main.cpp \
           src/main_window.cpp \
           src/config/cms_config_db.cpp \
           src/config/mbs_def.cpp \
           src/log/log_data_model.cpp \
           src/log/log_sender.cpp \
           src/log/log_server.cpp \
           src/log/log_widget.cpp \
           src/point/point_item_delegate.cpp \
           src/point/points_list_model.cpp \
           src/point/points_list_view.cpp \
           src/point/points_list_widget.cpp \
           src/tools/hex_convertor_widget.cpp \
           src/modbus/address/addr_space.cpp \
           src/modbus/address/addr_space_model.cpp \
           src/modbus/address/addr_space_view.cpp \
           src/modbus/analyzer/mbs_analyzer.cpp \
           src/modbus/comm/mbs_comm_model.cpp \
           src/modbus/comm/mbs_comm_view.cpp \
           src/modbus/config/config_item_delegate.cpp \
           src/modbus/config/master_config_model.cpp \
           src/modbus/config/master_config_view.cpp \
           src/modbus/diagram/crc_check.cpp \
           src/modbus/diagram/diagram_validator.cpp \
           src/modbus/diagram/mbs_serial_master.cpp \
           src/modbus/diagram/mbs_serial_req_handler.cpp \
           src/modbus/diagram/mbs_serial_response.cpp \
           src/modbus/diagram/mbs_tcp_master.cpp \
           src/modbus/diagram/mbs_tcp_req_handler.cpp \
           src/modbus/diagram/mbs_tcp_response.cpp \
           src/modbus/gui/addr_space_widget.cpp \
           src/modbus/gui/master_config_widget.cpp \
           src/modbus/gui/mbs_widget.cpp \
           src/modbus/io/mbs_serial_io.cpp \
           src/modbus/io/mbs_tcp_io.cpp \
           src/modbus/io/serial_master_session.cpp \
           src/modbus/io/serial_slave_session.cpp \
           src/modbus/io/tcp_master_session.cpp \
           src/modbus/io/tcp_slave_session.cpp \
           src/modbus/station/modbus_station.cpp \
           src/tools/serial_test/serial_test_widget.cpp
