#############################################################################
# Makefile for building: comm_svr_1_1_0
# Generated by qmake (2.01a) (Qt 4.8.6) on: Wed Jan 21 23:21:16 2015
# Project:  comm_svr_1_1_0.pro
# Template: app
# Command: k:\app_lib\qt-4.8.6-vc10\bin\qmake -o Makefile comm_svr_1_1_0.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = k:\app_lib\qt-4.8.6-vc10\bin\qmake
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: comm_svr_1_1_0.pro  k:\app_lib\qt-4.8.6-vc10\mkspecs\default\qmake.conf k:\app_lib\qt-4.8.6-vc10\mkspecs\qconfig.pri \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\modules\qt_webkit_version.pri \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\qt_functions.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\qt_config.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\win32-msvc2010\qmake.conf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\exclusive_builds.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\default_pre.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\default_pre.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\debug.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\debug_and_release.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\default_post.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\default_post.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\rtti.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\exceptions.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\stl.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\shared.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\embed_manifest_exe.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\embed_manifest_dll.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\warn_on.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\qt.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\thread.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\moc.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\windows.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\resources.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\uic.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\yacc.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\lex.prf \
		k:\app_lib\qt-4.8.6-vc10\mkspecs\features\include_source_dir.prf \
		k:\app_lib\qt-4.8.6-vc10\lib\qtmaind.prl
	$(QMAKE) -o Makefile comm_svr_1_1_0.pro
k:\app_lib\qt-4.8.6-vc10\mkspecs\qconfig.pri:
k:\app_lib\qt-4.8.6-vc10\mkspecs\modules\qt_webkit_version.pri:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\qt_functions.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\qt_config.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\win32-msvc2010\qmake.conf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\exclusive_builds.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\default_pre.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\default_pre.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\debug.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\debug_and_release.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\default_post.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\default_post.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\rtti.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\exceptions.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\stl.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\shared.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\embed_manifest_exe.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\embed_manifest_dll.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\warn_on.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\qt.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\thread.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\moc.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\win32\windows.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\resources.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\uic.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\yacc.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\lex.prf:
k:\app_lib\qt-4.8.6-vc10\mkspecs\features\include_source_dir.prf:
k:\app_lib\qt-4.8.6-vc10\lib\qtmaind.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile comm_svr_1_1_0.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
	-$(DEL_FILE) ".\comm_svr_1_1_0.intermediate.manifest"
	-$(DEL_FILE) comm_svr_1_1_0.exp
	-$(DEL_FILE) comm_svr_1_1_0.ilk
	-$(DEL_FILE) vc*.pdb
	-$(DEL_FILE) vc*.idb
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) comm_svr_1_1_0.pdb

check: first

debug-mocclean: $(MAKEFILE).Debug
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
